"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { WagmiConfig, createConfig, configureChains } from 'wagmi'
// import { createPublicClient, http } from 'viem'
// import { localhost } from 'wagmi/chains' 
// import { publicProvider } from 'wagmi/providers/public'
import {clientConf} from './components/client'
 

// const { publicClient } = configureChains([localhost], [publicProvider()])

// const config = createConfig({
//   autoConnect: true,
//   publicClient
// })

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config = {clientConf}>
        {children}
        </WagmiConfig>
        </body>
    </html>
  )
  
}
